### ISSUE TITLE
ironrdp-daemon test suite fails to compile on master: `consume_output` expects `OutputEventReceiver`, tests pass raw `mpsc::Receiver`

### ISSUE THREAD

**Issue by mamoreau-devolutions** [Devolutions/IronRDP#1830]
## Summary

`cargo test --workspace --locked --no-run` currently fails on `master` (verified at `4b7ef885f4604105d4fccaf2259afb410577f2c5`) because `crates/ironrdp-daemon/src/daemon.rs` has two test functions that construct a raw `tokio::sync::mpsc::channel(1)` and pass the resulting `Receiver<_>` into `consume_output`, which expects the `OutputEventReceiver` wrapper type introduced in #1815.

This breaks the `Tests (compile)` step in CI (`Checks [linux]` / `Checks [macos]`) for **any** PR that doesn't touch `ironrdp-daemon`, since the whole workspace is compiled together.

## Root cause

Introduced by #1822 ("fix(daemon): retain gateway error sources"), which added two new `#[tokio::test]` functions without updating them to build an `OutputEventReceiver` (the wrapper type added by #1815 for drop-policy classification) instead of a bare `mpsc::Receiver`.

## Errors

```
error[E0308]: mismatched types
   --> crates/ironrdp-daemon/src/daemon.rs:2239:13
    |
2238 |         let consumer = tokio::spawn(consume_output(
    |                                     -------------- arguments to this function are incorrect
2239 |             output_rx,
    |             ^^^^^^^^^ expected `OutputEventReceiver`, found `Receiver<_>`

error[E0308]: mismatched types
   --> crates/ironrdp-daemon/src/daemon.rs:2276:13
    |
2275 |         let consumer = tokio::spawn(consume_output(
    |                                     -------------- arguments to this function are incorrect
2276 |             output_rx,
    |             ^^^^^^^^^ expected `OutputEventReceiver`, found `Receiver<_>`
```

Affected tests:
- `connection_failure_status_preserves_gateway_error_sources` (`daemon.rs:2235`)
- `terminated_error_status_preserves_session_error_sources` (`daemon.rs:2272`)

## Impact

Any open PR's CI `Tests (compile)` step (Linux/macOS) fails regardless of what the PR itself changes, since `cargo test --workspace` compiles the entire workspace. Observed causing a false-negative CI failure on #1826.

## Suggested fix

Wrap the `mpsc::channel(1)` receiver into an `OutputEventReceiver` (matching how production call sites construct it) in both affected tests, or add a test-only `From`/constructor helper if `OutputEventReceiver` doesn't already expose one.

**Comment by glamberson** [comment]
Confirming this is resolved: We hit the same compile failure independently and filed #1832 with the same two-line fix, then closed it in favor of #1827, which carried the identical fix as part of its larger scope. #1827 merged the same day (13:22 UTC), about 13 hours after this issue was filed. Current `master`'s `daemon.rs` uses `output_channel(1)` correctly at every `consume_output` call site now, verified directly.

Should be safe to close whenever you get a chance.
